In [1]:
import pandas as pd

df = pd.read_csv('villas.csv')
df.drop([df.columns[0]], axis = 1, inplace=True)

In [4]:
df.shape

(76, 15)

In [5]:
df = df.drop_duplicates()

In [7]:
df

,Title,Price,Code,Location,Type of Sale,Lease Years,URL,Property Type,Year Built,Bedrooms,Bathrooms,Land Size (are),Building Size (sqm),Pool,Furnished
0,Luxurious and Stylish Villa in Gili Air For sale,"IDR 3,788,888,888",CVJ1433,Lombok,lease,29 years,https://www.villabalisale.com/property/villas-...,villa,NaN,2,2,3.00,165.00,yes,fully furnished
1,New 1 Bedroom Smart Home in Berawa for Sale,"IDR 2,572,247,433",CVES1436,Canggu,lease,28 years,https://www.villabalisale.com/property/villas-...,villa,NaN,1,1,0.50,63.68,yes,fully furnished
2,2 Bedroom Modern and Smart Living Townhouse in...,"IDR 3,934,025,487",CVES1429,Canggu,lease,28 years,https://www.villabalisale.com/property/villas-...,villa,NaN,2,2,0.90,92.00,yes,fully furnished
3,PEACEFUL AND SCENIC VILLA WITH RICE FIELD VIEW,"IDR 2,209,106,619",CVAS1394,Ubud,lease,21 years,https://www.villabalisale.com/property/villas-...,villa,NaN,2,2,6.00,110.00,yes,fully furnished
4,Upcoming stylish one bedroom villa for lease i...,"IDR 2,708,425,239",VL2702,Canggu,lease,24 years,https://www.villabalisale.com/property/villas-...,villa,Year Built: 2023,1,1,1.00,70.00,yes,fully furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,Beautiful 3 level ocean view villa for sale in...,"IDR 11,575,113,451",VL1568,Canggu,free,NaN,https://www.villabalisale.com/property/villas-...,villa,Year Built: 2009,2,2,5.84,185.00,yes,fully furnished
72,Three Bedroom Apartment Inside Five Star Resort,"IDR 4,950,000,000",VL2576,Nusadua,lease,28 years,https://www.villabalisale.com/property/villas-...,villa,Year Built: 2001,3,3,2.70,276.00,yes,fully furnished
73,Brand new leasehold property in Padonan,"IDR 3,011,042,584",VL2656,Padonan,lease,25 years,https://www.villabalisale.com/property/villas-...,villa,Year Built: 2023,1,2,1.37,129.00,yes,fully furnished
74,Beautiful Tropical Design 2 Bedroom Villa in t...,"IDR 5,471,617,358",PVSR024,Ubud,lease,29 years,https://www.villabalisale.com/property/villas-...,villa,Year Built: 2023,2,2,4.00,110.00,yes,fully furnished
75,Off-Plan Serene Studio Living in Ubud,"IDR 1,361,778,053",PVST049,Ubud,lease,30 years,https://www.villabalisale.com/property/villas-...,villa,Year Built: 2023,1,1,0.59,42.70,no,fully furnished